Pin requests-oauthlib<1.4.0 under python2.7
While requests-oauthlib 1.4.0 reports compatibility with python2.7
evidence points to the contrary. Specifically:

      import requests_oauthlib as oauth
    File "/home/zuul/src/opendev.org/zuul/zuul-jobs/.tox/py27/lib/python2.7/site-packages/requests_oauthlib/__init__.py", line 5, in <module>
      from .oauth1_session import OAuth1Session
    File "/home/zuul/src/opendev.org/zuul/zuul-jobs/.tox/py27/lib/python2.7/site-packages/requests_oauthlib/oauth1_session.py", line 1, in <module>
      from urllib.parse import urlparse
  ImportError: No module named parse

The azure-storage-blob library depends on this oauthlib which is needed
for log upload role testing. We address that by pinning the lib under
python2.7.

Change-Id: Ia27f2df166ccb33dcc93334d884411670ac859f7